### ISSUE TITLE
Progress bar not showing up on default theme.

### ISSUE THREAD

**Issue by mattmeng** [jdan/cleaver#148]
I noticed that the progress bar wasn't showing up on the default theme, even after explicitly turning it on.  I found that adding the following stylesheet fixed the issue:

``` css
.progress {
  z-index: 1000;
}
```
