### ISSUE TITLE
Feature: Export PDF via Chrome `Print...`

### ISSUE THREAD

**Issue by anqurvanillapy** [jdan/cleaver#169]
- This feature could be easily achieved by this:

```css
@media print {
  .some-slide-container {
    page-break-after: always !important;
  }
  .some-slide-container:last-of-type {
    page-break-after: avoid !important;
  }
}
```

- Here is a [HTML template](https://github.com/anqurvanillapy/gmhp/blob/master/gmhp/templates/index.tmpl) from my legacy similar Markdown-based slideshow generator in Python
- I thought it might be a good workaround when encountering some low-version browsers by using PDF slideshow

**Comment by jdan** [comment]
We have some similar code in [`default.css`](https://github.com/jdan/cleaver/blob/master/resources/default.css#L246-L249)

```css
.slide:nth-child(even) {
    /* 2 slides per page */
    page-break-before: always;
}
```

Does that cover it?
