### ISSUE TITLE
cleaver.json

### ISSUE THREAD

**Issue by jdan** [jdan/cleaver#89]
## A modest proposal

I'd like to start a conversation about this.

Currently, cleaver presentations contain metadata:

```
title: My presentation
author:
    name: Jordan Scales
    twitter: @jdan
output: talk.html
style: something.css

--

# My presentation
## It has a subtitle
```

This is, in my opinion, a little weird. I would like to separate documents into two parts: the actual presentation (_just_ markdown) and a new file called **cleaver.json**, which may look like this:

```
{
  "title": "My presentation",
  "style": "something.css",
  "author": {
    "name": "Jordan Scales",
    "url": "http://jscal.es",
    "twitter": "@jdan"
  },
  "output": "talk.html"
}
```

I'd also like to reopen the possibility of handling command-line options (we used to do this)

```
cleaver presentation.md --style=something.css --output=talk.html
```

so you could avoid creating a **cleaver.json**.
## Benefits

**Separation of presentation content and settings**. I feel like having the content and settings tightly coupled is a little counterintuitive. We could keep things more organized, which could open the door to a few new features - plugins, middleware, that sort of thing.
## Downsides

**No longer one file :(**. The whole idea is that cleaver presentations are super portable, both when they're being creating and when they're rendered. You can still have your entire presentation contained in a single file, though, and simply use command-line options to achieve what you can now.

What are your thoughts?
